### ISSUE TITLE
编译本地项目报错

### ISSUE THREAD

**Issue by freeNestor** [crazy-max/xgo#93]
使用mac ventura 13.2交叉编译本地项目报错，是什么问题，有解决方案吗？
(Cross-compiling local projects with mac ventura 13.2 occurs an error. What is the problem and is there a solution?)

·> xgo -targets=linux/amd64 -tags='nodb2' ./cmd/tool/encrypt.go 
INFO: Starting xgo/dev
INFO: Checking docker installation...
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.41 (downgraded from 1.42)
 Go version:        go1.19.5
 Git commit:        e92dd87c32
 Built:             Tue Jan 31 16:45:07 2023
 OS/Arch:           darwin/arm64
 Context:           default

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

INFO: Checking for required docker image ghcr.io/crazy-max/xgo:latest... 
INFO: Docker image found!
DBG: config: &{Repository:./cmd/tool/encrypt.go Package: Prefix: Remote: Branch: Dependencies: Arguments: Targets:[linux/amd64]}
DBG: flags: &{Verbose:false Steps:false Race:false Tags:nodb2 LdFlags: Mode:default VCS: TrimPath:false}
INFO: Cross compiling ./cmd/tool/encrypt.go package...
INFO: Completed!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1010ed298]

goroutine 1 [running]:
main.compile({0x14000094000, 0x1c}, 0x140000a4000, 0x14000092050, {0x14000028084, 0x3c})
	/Users/engfall/Documents/90-Develop/go-src/pkg/mod/github.com/crazy-max/xgo@v0.24.0/xgo.go:333 +0xc48
main.main()
	/Users/engfall/Documents/90-Develop/go-src/pkg/mod/github.com/crazy-max/xgo@v0.24.0/xgo.go:188 +0x920

**Comment by freeNestor** [comment]
Solved by myself. Thx
